project_gains/WorkoutApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = "WorkoutApp" #this is app name for the urls;it helps uniquely identify all of the urls
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'), #copy pasted code for template name thing
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.create_user, name='signup'),
    path('contribute/', views.contribute, name='contribute'),
    path('search/', views.search, name='search'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('about/',views.about, name='about'),
    path('savepost/<int:pk>/', views.savepost, name="savepost")
]

project_gains/project_gains/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('WorkoutApp/', include("WorkoutApp.urls")),
    path('accounts/', include('django.contrib.auth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_gains/WorkoutApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.apps import apps #from stackoverflow 
from django.db.models import Sum #from another stackoverflow post https://stackoverflow.com/questions/56046688/how-to-get-the-sum-of-a-field-in-django
from django.db.models import Avg
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.
#personal observation: like in cpp the function order matters here(i.e when Hashtag was below Post there was a warning that Hashtag was not created or smthng?)
"""
def get_avg_rating(url):
    Post = apps.get_model(app_label='WorkoutApp', model_name='Post')
    #Video = apps.get_model(app_label='WorkoutApp', model_name='Video')
    video_n =  Post.objects.filter(url = url).count() #* Task.DEFAULT_VALUE
    print(video_n)
    sum = Post.objects.filter(url=url).aggregate(sum_of_rating=Sum("rating"))
    return video_n/sum
"""


class Hashtag(models.Model):
    hashtag = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.hashtag}"


class Video(models.Model):
    url = models.URLField()

   # ratings = models.ForeignKey(Post)
    #avgrating = models.IntegerField(null=True, blank=True, default=get_avg_rating(url))



#url and author changed from foreign key to onetoone field because
#In contrast to the OneToOneField "reverse" relation, a ForeignKey "reverse" relation returns a QuerySet.
class Post(models.Model):
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.ForeignKey(Video,on_delete=models.CASCADE) #ManyToOne because each post can have one video but each video has multiple people posting about it 
    hashtag = models.ManyToManyField(Hashtag) #because each post can have multiple tags and tags can be included in multiple posts
    opinion = models.CharField(max_length=200)
    rating = models.IntegerField() # same as url but i want it to be in Video so i can later calculate universal ranking of each individual video
    #comment_rating = models.IntegerField()
    #comment_opinio = models.CharField(max_length = 200)
    comments = models.ManyToManyField('self', symmetrical=False, blank = True, null=True, related_name='PostCom')

    def __str__(self):
        return f"{self.author} - {self.opinion}"

class AccGroup(models.Model):
    name = models.CharField(max_length=128)
    members = models.ManyToManyField(User)

    def __str__(self):
        return self.name
    
class UserProfile(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    profile_pic = models.ImageField('profile picture', upload_to='media/WorkoutApp/', null=True, blank=True, default="media/WorkoutApp/defaultavatar.jpg")
    bio = models.CharField(max_length=300, null=True)
    banner_pic = models.ImageField('banner pic', upload_to='media/WorkoutApp/banners', null=True, blank=True, default="media/WorkoutApp/banners/yes4.jpg")
    saved_posts = models.ManyToManyField(Post)
    def __str__(self):
        return f"{self.name}"
    
    

project_gains/WorkoutApp/forms.py
from django import forms
from django.forms import MultiWidget, TextInput  #for the placeholder

class NewPostForm(forms.Form):
    opinion = forms.CharField(label="workout_opinion")
    rating = forms.IntegerField(max_value=10, min_value=1, label="workout_rating")

class NewVideo(forms.Form):
    url = forms.URLField(label="workout_url")
  
class NewHashtag(forms.Form):
    hashtag = forms.CharField(widget=TextInput(attrs={'placeholder': '#UpperBody'}), label="workout_hashtag")
class LoginUser(forms.Form):
    user_name = forms.CharField(max_length=50)
    password = forms.CharField(max_length = 50)

class ChangeProfile(forms.Form):
    avatar = forms.ImageField(required=False)
    bio = forms.CharField(required=False)
    banner = forms.ImageField(required=False)

project_gains/WorkoutApp/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render,redirect
from django.template import loader
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib import messages #django flash messages
from django.contrib.auth import login, authenticate
from .forms import NewHashtag, NewPostForm, NewVideo, LoginUser, ChangeProfile
from WorkoutApp.models import Video, Post, Hashtag, UserProfile, AccGroup
from django.utils import timezone
from django.db.models import Avg
from django.shortcuts import get_object_or_404
from django.urls import resolve
from django.utils import timezone, dateformat #maybe not needed
from calendar import HTMLCalendar
from datetime import datetime, date




# Create your views here.


def about(request):
    return render(request, 'WorkoutApp/about.html')

def create_user(request):
    template = loader.get_template('registration/signup.html')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, 'You have singed up successfully.')
            
            user_profile = UserProfile.objects.create(name=user)
            user_profile.save()
            login(request, user)
            #UserProfile.objects.create(name=user)
            template2 = loader.get_template('WorkoutApp/index.html')
            context = {
                'tasks': Post.objects.filter(PostCom=None),
                "formpost": NewPostForm(),
                'comments':Post.objects.all(),
                'avg_rating': Video.objects.values("url").annotate(average_rating=Avg("post__rating")),
                'accgroups': AccGroup.objects.all()
            }
            #return HttpResponse(template2.render(context,request))
            return HttpResponseRedirect(reverse("WorkoutApp:index"))
            #return redirect('./WorkoutApp/index.html')
        else:
            return HttpResponse(template.render({'form':form}, request))
           # return render(request, 'registration/signup.html', {'form': form})
    else:
        messages.success(request, 'you are here.')
        form = UserCreationForm()
        context = {'form': form}
        template = loader.get_template('registration/signup.html')
        return HttpResponse(template.render(context, request))
"""   
def loginuser(request):
    context = {
        'form': LoginUser(request.POST)

    }
    #if request.user.is_authenticated:

    template = loader.get_template('registration/login.html')
    return HttpResponse(template.render(context, request))
"""

#from IPython.display import HTML

# Based on https://stackoverflow.com/a/1458077/1639671
class HighlightedCalendar(HTMLCalendar):
    def __init__(self, highlight=[], *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._highlight = highlight
    
    def formatday(self, day, weekday):
        """
        Return a day as a table cell.
        """
        cssclass = self.cssclasses[weekday]
        if date.today() == date(self.year, self.month, day):
            cssclass += ' today'
        if day in self.workouts:
            cssclass += ' filled'
            
            return self.day_cell(cssclass, '%d %s' % (day, ''.join(body)))
        return self.day_cell(cssclass, day)
    
    def day_cell(self, cssclass, body):
        return '<td class="%s">%s</td>' % (cssclass, body)

from itertools import groupby

from django.utils.html import conditional_escape as esc

class WorkoutCalendar(HTMLCalendar):

    def __init__(self, workouts):
        super(WorkoutCalendar, self).__init__()
        self.workouts = self.group_by_day(workouts)

    def formatday(self, day, weekday):
        if day != 0:
            cssclass = self.cssclasses[weekday]
            if date.today() == date(self.year, self.month, day):
                cssclass += ' today'
            if day in self.workouts:
                cssclass += ' filled'
                #body = ['<ul>']
                #for workout in self.workouts[day]:
                 #   body.append('<li>')
                  #  body.append('<a href="%s">' % workout.url.url)
                  #  body.append(esc(workout.rating))
                  #  body.append('</a></li>')
                #body.append('</ul>')
                #return self.day_cell(cssclass, '%d %s' % (day, ''.join(body)))
            return self.day_cell(cssclass, day)
        return self.day_cell('noday', '&nbsp;')

    def formatmonth(self, year, month):
        self.year, self.month = year, month
        return super(WorkoutCalendar, self).formatmonth(year, month)

    def group_by_day(self, workouts):
        field = lambda workout: workout.pub_date.day
        return dict(
            [(day, list(items)) for day, items in groupby(workouts, field)]
        )

    def day_cell(self, cssclass, body):
        return '<td class="%s">%s</td>' % (cssclass, body)


def profile(request, username=None):
        if username:
            print(username)
            user = get_object_or_404(User, username=username)
        else:
            user = request.user
        
        date_year = timezone.now().year
        date_month = timezone.now().month
        #cal = HTMLCalendar().formatmonth(date_year,date_month)

        userposts= Post.objects.filter(pub_date__year=date_year, 
                      pub_date__month=date_month, author__username = username)
        print(userposts)
        highlight = [1,2,3,4,5,6,7]
        #myset = set()
        #for dateobj in userposts:
            #for x,y in dateobj.items(): #https://stackoverflow.com/questions/64374956/print-values-of-dictionary-one-by-one
                #highlight.append(y.day)
         #       if y in highlight:
          #          print("its in here")
           #     else:
                    #highlight.append(int(y.day))
            #        print(type(int(y.day)))
        #print(myset)
        #highlight = list(myset)
        print(highlight)
        #days = datetime.strptime(userposts[1][1], '%d')
        #print(userposts)
        cal = WorkoutCalendar(userposts).formatmonth(date_year, date_month)
        #cal = HighlightedCalendar(highlight=highlight).formatmonth(date_month, date_year)
        profile = get_object_or_404(UserProfile, name__username=user.username)
        print(profile.bio)
        args = {
            'user': user,
            'cal': cal,
            'tasks': Post.objects.filter(author__username= user.username),
            'image': profile, 'formpost': NewPostForm(), 
            'avg_rating': Video.objects.values("url").annotate(average_rating=Avg("post__rating")),
            'daterange': userposts,
        }
        return render(request, 'WorkoutApp/profile.html', args)


def savepost(request, pk=None):
    post = get_object_or_404(Post, id=pk)
    userprofile = UserProfile.objects.get(name=request.user)
    userprofile.saved_posts.add(post)
    messages.success(request, 'Profile details updated.')
    return redirect('WorkoutApp:index')



def index(request):
    context = {
    'tasks': Post.objects.filter(PostCom=None),
    "formpost": NewPostForm(),
    'comments':Post.objects.all(),
    'avg_rating': Video.objects.values("url").annotate(average_rating=Avg("post__rating")),
    'accgroups': AccGroup.objects.all(),
    #'image': UserProfile.objects.get(name = request.user),
    'profile': UserProfile.objects.filter()
    }

    #video_id = Video.objects.values("url").url
    #print('http://youtube.com/embed/%s' % video_id[0])
    #if request.user.is_authenticated:
    #query = request.GET.get('search')
    #if query:
     #   context['object_list'] = Post.objects.filter(opinion__icontains=request.GET.get('search'))
     #https://stackoverflow.com/questions/69964943/how-to-put-button-value-to-database-django
    
    template = loader.get_template('WorkoutApp/index.html')
    return HttpResponse(template.render(context, request))


def search(request):
    context = {
    'tasks': Post.objects.filter(PostCom=None),
    "formpost": NewPostForm(),
    'comments':Post.objects.all(),
    'avg_rating': Video.objects.values("url").annotate(average_rating=Avg("post__rating")),
    }
    

    #if request.user.is_authenticated:
    query = request.GET.get('search')
    if query:
        context['object_list'] = Post.objects.filter(opinion__icontains=query)
    template = loader.get_template('WorkoutApp/search.html')
    return HttpResponse(template.render(context, request))


@login_required
def contribute(request):
    template = loader.get_template('WorkoutApp/index.html') 
    context = {
       # "formurl": NewVideo(),
        "formpost": NewPostForm(),
        #"formtag": NewHashtag()
    }
    if request.method == "POST":
        form = NewPostForm(request.POST)
        form_data = request.POST
        if form.is_valid():
            url = form_data["url_hidden"]
            v = Video.objects.get(url = url)
            #v.save()
            posto = form.cleaned_data["opinion"]
            postr = form.cleaned_data["rating"]
            p = Post(opinion=posto, pub_date=timezone.now(), rating=postr, author= request.user, url= v)
            p.save()
            hashtag = form_data["tag_hidden"]
            print(hashtag)
            x = hashtag.split(" ")
            for i in x:
                a = Hashtag.objects.get(hashtag=i)
                
                #if Hashtag.objects.filter(hashtag__hashatag=i).exists():
                print("exists")
                         #found.save()
                p.hashtag.add(a)
            originalpost_opinion = form_data["oposto_hidden"]
            o = Post.objects.get(opinion=originalpost_opinion)
            o.comments.add(p)
            o.save()

project_gains/WorkoutApp/templates/WorkoutApp/add.html
{% extends "WorkoutApp/layout.html" %}
{% block body %}
  <h1>Add Workout</h1>
  <form action="{% url 'WorkoutApp:add' %}" method="post" class="neonText">
    {% csrf_token %}
    {{ formurl.as_p }}
    {{ formpost.as_p}}
    <span style="color: rgb(138, 67, 147);">please ensure that incase of multiple tags, tags are separated by a space</span>
    {{ formtag.as_p}}
    <input type="submit">
  </form>
  <a href="{% url 'WorkoutApp:index' %}">BACK TO HOMEPAGE</a>

{% endblock %}

project_gains/WorkoutApp/templates/WorkoutApp/index.html
{% extends "WorkoutApp/layout.html" %}
{% block body %}
{% load static %}


<div id="test">
	<img id="logo" src="{% static 'WorkoutApp/PixCut-removebg_thumbnail.png' %}"
		style="float: left;width: 4%;height: auto;margin-top: 5px;">
	<a href="{% url 'WorkoutApp:about' %}" style="margin-top: 5px;">About</a>
	<!--input type="search" style="margin: 10px 40px;" placeholder="Search" /-->
	<form action="{% url 'WorkoutApp:search' %}" method="get"
		style="position: absolute;top: 5px !important;left: 115px;">
		<input style="margin: 13px 10px;" type="text" name="search" placeholder="Search by tag or keywords"
			value="{{request.GET.search}}">
		<input type="submit" value="Search" id="search">
	</form>
	<div
		style="position: absolute;top: 0px !important;right: 0px !important;width: 40%;height: 100%;text-align: end;padding-top: 2px;">
		{% if request.user.is_authenticated %}
		<a href="{% url 'WorkoutApp:profile' request.user %}">
			<img src="{{ request.user.userprofile.profile_pic.url }}" alt="" width="45px" height="45px"
				style="border-radius: 50%;border: 2px solid white;position: absolute;top: 5px;float: left;right:22%">
		</a>

		<a href="{% url 'logout' %}" style="position: absolute;right: 5%;">Sign out</a>
		{% else %}
		<a href="{% url 'WorkoutApp:signup' %}">Sign up</a>
		<a href="{% url 'WorkoutApp:login' %}">Sign in</a>
		{% endif %}
	</div>
</div>
<div class="row">
	<div class="column middle">
		{% for q in tasks %}

		<div class="post-div">
			<a href="{% url 'WorkoutApp:profile' q.author %}">
				<img src="{{ q.author.userprofile.profile_pic.url }}" alt="" width="55px" height="55px"
					style="border-radius: 50%;border: 1px solid white;position: absolute;top: 10px;left:5px;">
			</a>
			<a href="{% url 'WorkoutApp:profile' q.author %}" class="author"
				style="text-decoration: none; font-size: 12px;position: absolute;top: 17px;left: 70px;color: #4f7cac;">
				{{ q.author.username }}</a>
			<div
				style="position: absolute;left:70px;text-align: start; top: 65px;line-height: 115%;height:75%;width:50%;border: 2px solid green;">

				<!--<iframe src="{{ q.url.url }}" height="200" width="200">media</iframe-->
				<a class="url" href="{{ q.url.url }}">Link</a>
				{% for x in avg_rating.all %}

				{% if x.url == q.url.url %}

				<p style="font-size: 12px;">Average Rating: {{ x.average_rating|floatformat:2 }}<span
						style="font-size: 10px;"> /10</span></p>
				{% endif %}
				{% endfor %}
				<h5 style="font-size: small;" class="originalposto">{{ q.opinion }}</h5>
				<p class="rating" style="font-size: 14px;">Personal Rating: {{ q.rating }}<span
						style="font-size: 10px;"> /10</span></p>
				<p style="font-size: x-small;">{{ q.pub_date }}</h6>
					<br>
					<br>
				<div style="position: absolute;width: 100%;height:12%;border: 2px solid goldenrod;display: flex;
						flex-wrap: nowrap;">
					{% for hashtag in q.hashtag.all %}
					<p style="font-size: small;" class="tag_text">{{ hashtag.hashtag }} </p>
					{% endfor %}
					{% if request.user.is_authenticated %}
					<a href="{% url 'WorkoutApp:savepost' q.id %}" ><div class="trapezoid" id="myTrap{{ forloop.counter0 }}"></div></a>
						{% endif %}
					</div>

			</div>
			<div class="comment">
				<p>Comments:</p>
				<br>
				{% for i in q.comments.all %}
				<p style="color:#5a7aa9; font-size: x-small;"><strong>{{ i.author }} : </strong> {{ i.opinion }}
				</p>
				{% endfor %}
				<button id="openform{{ forloop.counter0 }}" class="open-button">Tried it!</button>
			</div>

			<div class="form-popup" id="myForm{{ forloop.counter0 }}">
				<form action="{% url 'WorkoutApp:contribute' %}" method="post" class="form-container contactForm">
					{% csrf_token %}
					<h3 style="color: #0B7A75;">Comment:</h3>
					<input type="hidden" value="#" class="url_hidden" name="url_hidden" />
					<input type="hidden" class="tag_hidden" name="tag_hidden" />
					<input type="hidden" class="originalposto_hidden" name="oposto_hidden" />
					{{ formpost.as_p }}
					<button type="submit" class="btn">Post</button>
					<!--button id="clicky{{ forloop.counter0 }}" type="button" class="btn clicky" >Check</button-->
					<button id="closeform{{ forloop.counter0 }}" type="button"
						class="btn cancel closeform">Close</button>
				</form>
			</div>
		</div>
		{% endfor %}
		<br>
		<div style="position: absolute;align-content: center;">
			<!--a href="{{request.user}}" class="neonText">GO to Profile</a-->
			{% if request.user.is_authenticated %}
			<a href="{% url 'WorkoutApp:add' %}" class="neonText">Add New Workout</a>
			<a href="{% url 'logout' %}" class="neonText">LOGOUT</a>
			{% else %}
			<a href="{% url 'WorkoutApp:add' %}" class="neonText">Add New Workout</a>
			{% endif %}
		</div>
	</div>


	<div class="column side">
		<p>HELOO WORLD</p>
		{% for group in accgroups %}
		<div>
			<h4>{{group.name}}</h4>
			{% for member in group.members.all %}
			<p>{{member.username}}</p>
			{% endfor %}
		</div>
		{% endfor %}

	</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
	$(document).ready(function () {

		$(".open-button").click((clicked) => {
			var id = clicked.target.id;
			//alert(id);
			var matches = id.match(/\d+$/);
			if (matches) {
				var numString = matches[0];
				//alert(numString);
				$("#myForm" + numString).css("display", "block");
			}

			var temp_string = "";
			$("#" + id).parentsUntil(".post-div").siblings(".tag_text").css('color', 'yellow');
			$("#" + id).parentsUntil(".post-div").siblings(".tag_text").each(function () {
				temp_string += $(this).text() + " ";
			});
			//alert(temp_string);
			$(".tag_hidden").val(temp_string);
			$("#" + id).parentsUntil(".post-div").siblings(".url").css('color', 'red');
			var url = $("#" + id).parentsUntil(".post-div").siblings(".url");
			$(".url_hidden").val(url.attr('href'));
			//the below code is for original post opinion input
			//works//$("#" + id).parentsUntil(".post-div").siblings(".originalposto").css('color', 'red');
			var o = $("#" + id).parentsUntil(".post-div").siblings(".originalposto");
			$(".originalposto_hidden").val(o.text());

		});

	});
	$(document).ready(function () {
		$(".closeform").click((clicked) => {
			//alert("you are here");
			var idd = clicked.target.id;
			//alert(idd);
			var matches = idd.match(/\d+$/);
			if (matches) {
				var numString = matches[0];
				//alert(numString);
				var go = "#myForm" + numString;
				//alert(go);
				$("#myForm" + numString).css("display", "none");
				//document.getElementById(go).style.display = "none";
			}

		});

	});
</script>
{% endblock %}

project_gains/WorkoutApp/templates/WorkoutApp/search.html
{% extends "WorkoutApp/layout.html" %}
{% block body %}

<div class="topnav">
	<a href="#" style="padding: 10px 40px;">About</a>
	<!--input type="search" style="margin: 10px 40px;" placeholder="Search" /-->
	<form action="">
		<input style="margin: 10px 40px;" type="text" name="search" placeholder="Search by tag or keywords" value="{{request.GET.search}}">
		<input type="submit" value="Search" id="search" >
	</form>
</div>
<div class="row">
	<div class="column middle">
		{% for q in object_list %}

		<div class="post-div">
			<p class="author" style="font-size: x-small;">{{ q.author }}</p>
			<!--<iframe src="{{ q.url.url }}" height="200" width="200">media</iframe-->
			<a class="url" href="{{ q.url.url }}">video</a>
			{% for x in avg_rating.all %}
				
				{% if x.url == q.url.url %}
					
					<p style="font-size: x-small;">Average Rating: {{ x.average_rating|floatformat:2 }}/10</p>
				{% endif %}
			{% endfor %}
			<p style="font-size: small;" class="originalposto">{{ q.opinion }}</p>
			<p class="rating" style="font-size: small;">Rating: {{ q.rating }}</p>
			{% for hashtag in q.hashtag.all %}
			<p style="font-size: small;" class="tag_text">{{ hashtag.hashtag }}</p>
			{% endfor %}
			<p style="font-size: x-small;">{{ q.pub_date }}</h6>
			<button id="openform{{ forloop.counter0 }}" class="open-button">tried it</button>
			<div class="comment">
				<p>Comments:</p>
					{% for i in q.comments.all %}
						<p style="color:white; font-size: x-small;" ><strong>{{ i.author }} : </strong> {{ i.opinion }}</p>
					{% endfor %}
			</div>
				

			<div class="form-popup" id="myForm{{ forloop.counter0 }}">
				<form action="{% url 'WorkoutApp:contribute' %}" method="post" class="form-container contactForm">
					{% csrf_token %}
					<h3 style="color: #0B7A75;">Comment:</h3>
					<input type="hidden" value="#" class="url_hidden" name="url_hidden"/>
					<input type="hidden" class="tag_hidden" name="tag_hidden"/>
					<input type="hidden" class="originalposto_hidden" name="oposto_hidden"/>
					{{ formpost.as_p }}
					<button type="submit" class="btn">Post</button>
					<!--button id="clicky{{ forloop.counter0 }}" type="button" class="btn clicky" >Check</button-->
					<button id="closeform{{ forloop.counter0 }}" type="button"
						class="btn cancel closeform">Close</button>
				</form>
			</div>
		</div>
		{% endfor %}
		<br>
		<a href="{% url 'WorkoutApp:index' %}" class="neonText">Back to Homepage</a>
        <br>
		{% if request.user.is_authenticated %}
		<a href="{% url 'WorkoutApp:add' %}" class="neonText">Add New Workout</a>
		<a href="{% url 'logout' %}" class="neonText">LOGOUT</a>
		<a href="{% url 'WorkoutApp:profile' request.user %}" class="neonText">GO to Profile</a>
		{% else %}
		<a href="{% url 'WorkoutApp:add' %}" class="neonText">Add New Workout</a>
		{% endif %}
		
	</div>
	

	<div class="column side">
		<p>HELOO WORLD</p>
		
	</div>
    
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
	$(document).ready(function () {

		$(".open-button").click((clicked) => {
			var id = clicked.target.id;
			//alert(id);
			var matches = id.match(/\d+$/);
			if (matches) {
				var numString = matches[0];
				//alert(numString);
				$("#myForm" + numString).css("display", "block");
			}

			var temp_string = "";
			$("#" + id).parentsUntil(".post-div").siblings(".tag_text").css('color', 'yellow');
			$("#" + id).parentsUntil(".post-div").siblings(".tag_text").each(function () {
				temp_string += $(this).text()+" ";
			});
			//alert(temp_string);
			$(".tag_hidden").val(temp_string);
			$("#" + id).parentsUntil(".post-div").siblings(".url").css('color', 'red');
			var url = $("#" + id).parentsUntil(".post-div").siblings(".url");
			$(".url_hidden").val(url.attr('href'));
			//the below code is for original post opinion input
			//works//$("#" + id).parentsUntil(".post-div").siblings(".originalposto").css('color', 'red');
			var o = $("#" + id).parentsUntil(".post-div").siblings(".originalposto");
			$(".originalposto_hidden").val(o.text());

		});

	});
	$(document).ready(function () {
		$(".closeform").click((clicked) => {
			//alert("you are here");
			var idd = clicked.target.id;
			//alert(idd);
			var matches = idd.match(/\d+$/);
			if (matches) {
				var numString = matches[0];
				//alert(numString);
				var go = "#myForm" + numString;
				//alert(go);
				$("#myForm" + numString).css("display", "none");
				//document.getElementById(go).style.display = "none";
			}

		});
		
	});
</script>
{% endblock %}